on:
  push:
    tags:
      - "v*"
name: Create Release
jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      ASSET_FILES: LICENSE README.md access_point_config.tar.gz fix_avatar_colors_for_overlay font schedules static
          switch_config.txt templates tunnel
    steps:
      - name: Set additional environment variables
        run: |
          echo ::set-env name=TAG::$(echo ${GITHUB_REF:10})
          echo ::set-env name=LINUX_X64_FILENAME::$(echo cheesy-arena.${TAG}.linux.x64.zip)
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Linux bundle
        run: |
          rm -rf cheesy-arena*
          mkdir cheesy-arena
          GOOS=linux GOARCH=amd64 go build -o cheesy-arena/
          cp -r ${{ env.ASSET_FILES }} cheesy-arena/
          zip -r -X ${{ env.LINUX_X64_FILENAME }} cheesy-arena
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Cheesy Arena ${{ github.ref }}
          body: This is a release of Cheesy Arena for the 2020-2021 FRC game, INFINITE RECHARGE. Download the version
              for your operating system below. Supported operating systems are Linux, macOS (x64 and M1), and Windows.
          draft: false
          prerelease: false
      - name: Upload Linux bundle
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.LINUX_X64_FILENAME }}
          asset_name: ${{ env.LINUX_X64_FILENAME }}
          asset_content_type: application/zip
